version: "3.9"
   
#services:
#  db
#  server:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    ports:
#      - "8000:8000"
#      - "3307:3306"
 
 
services:
  db:
    image: mysql:5.7
    ports:
      - '3307:3306'
    environment:
       MYSQL_DATABASE: 'banking'
       MYSQL_ROOT_PASSWORD: 'toor'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/django-server
    ports:
      - "8000:8000"
    environment:
       DATABASE_HOST_DB: 'banking'
       DATABASE_PWD: 'toor'
       DATABASE_HOST_DB: "db"
       DATABASE_HOST_PORT: ""
    depends_on:
      - db
