# Generated by Django 3.1.5 on 2021-02-02 11:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by', to='core.bankcustomer', verbose_name='Auftraggeber'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='execute_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 12, 46, 29, 396046)),
        ),
    ]
