# Generated by Django 3.1.5 on 2021-02-02 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210202_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='execute_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
