# Generated by Django 3.1.3 on 2020-11-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='')),
                ('message', models.CharField(max_length=280)),
                ('uuid', models.CharField(max_length=128)),
            ],
        ),
    ]
